### ISSUE TITLE
response-policy有什么意义和作用？

### ISSUE THREAD

**Issue by HuanMeng0** [zyqf/DNS#10]
在rpz分支看到如下代码：
response-policy { 
   		zone "rpz.zone" policy given; 
	};

请问有什么意义和作用？

**Comment by zyqf** [comment]
主要是需要定义 A 记录的域名、子域名太多，有时候并不能用*解决，在 rpz 里的返回自定义 A 记录，不在的去递归或者向上游 DNS 查询 
bind9 的 rpz 类似 unbound 的 local-zone ，你可以参考 https://github.com/CNMan/unbound.conf/blob/master/unbound.local-zone.hosts.conf

**Comment by HuanMeng0** [comment]
那么删除这段代码是否有影响？

**Comment by zyqf** [comment]
旧的分支不会，但是新的分支会有影响，以后都以rpz作为默认分支维护更新

**Comment by HuanMeng0** [comment]
我的意思是，删除这段代码是否会影响使用？

**Comment by zyqf** [comment]
rpz分支会受到影响，导致无法正常工作！response-policy最好只有一个区域，过多的区域会影响DNS服务器性能。您提供的数据我已经合并到了rpz，你可以参考现在的代码。

**Comment by HuanMeng0** [comment]
好的。

请问DEMO DNS什么时候更新？

**Comment by zyqf** [comment]
明天晚上会写自动更新rpz.zone的脚本，还要在虚拟机里面测试下，测试好了，才可以更新。大概2日内就好了。

**Comment by HuanMeng0** [comment]
了解
