### ISSUE TITLE
一个雏形的一键安装脚本(Only CentOS)

### ISSUE THREAD

**Issue by HuanMeng0** [zyqf/DNS#15]
https://github.com/HuanMeng0/DNS/tree/dev

**Comment by zyqf** [comment]
如果要支持rpz，需要编译安装bind9.10.3.之前直接安装rpm有依赖问题。直接yum install bind 是不可以的

**Comment by HuanMeng0** [comment]
能否把我的dev分支合并进去？可能是你没有创建dev分支，我无法发起pull request

**Comment by HuanMeng0** [comment]
且希望能把我添加进Collaborators

**Comment by zyqf** [comment]
分支已建立，已加入。欢迎！

**Comment by HuanMeng0** [comment]
谢谢。
