### ISSUE TITLE
ubuntu怎么弄

### ISSUE THREAD

**Issue by sakz** [zyqf/DNS#2]
安装好目录没有对应的文件

**Comment by Debiancc** [comment]
老乡开门 社区送温暖

**Comment by zyqf** [comment]
参考
http://chengyue2007.iteye.com/blog/463008

多用百度和google,谢谢

**Comment by zyqf** [comment]
http://wiki.ubuntu.org.cn/Bind9%E5%AE%89%E8%A3%85%E8%AE%BE%E7%BD%AE%E6%8C%87%E5%8D%97
