### ISSUE TITLE
某些域名无法解析&初次解析会超时

### ISSUE THREAD

**Issue by HuanMeng0** [zyqf/DNS#20]
某些域名无法解析：
![84b696d893e20067fed01f1595b68944.png](http://moefq.com/images/2016/03/12/84b696d893e20067fed01f1595b68944.png)

初次解析会超时：
![d745cada2590d598618a499d618cfb11.png](http://moefq.com/images/2016/03/12/d745cada2590d598618a499d618cfb11.png)

**Comment by zyqf** [comment]
建议执行： nslookup xx.fbcdn.net  公网IP
另外：如果要在docker环境下搭建，请把bin/Dockerfile 文件移至项目的根目录

**Comment by HuanMeng0** [comment]
那么如何解决首次解析会超时？

**Comment by codexss** [comment]
后面cmd就是公网查询的，问题依旧…

**Comment by zyqf** [comment]
第一次超时，这怎么能解决。第一次解析都要去根服务器查询，查询成功了会自动缓存到本地，下次就直接调用本地缓存，才不会解析超时。阿里云，114等，解析冷门域名的时候，超时也是经常发生的。

**Comment by codexss** [comment]
超时严重的话客户端查询多次都出不来结果，我现在尝试取消从根服务器查询替换为从科大DNS取结果。

**Comment by codexss** [comment]
还有一点就是bind的rpz.zone有结果的话也会有延迟，貌似会从十三个根服务器走一遍…

**Comment by codexss** [comment]
named.conf修改为这个，效果改善了很多，以下三个ip都是科大的防污染DNS
zone "." IN {
        type forward;
        forwarders { 202.38.93.153;202.141.162.123;202.141.176.93; };
};
