### ISSUE TITLE
能否出一份中文dns自建教程及这个项目的上游DNS是哪个？

### ISSUE THREAD

**Issue by wpyok500** [zyqf/DNS#22]
1、能否出一份中文dns自建教程
2、这个项目的上游DNS是哪个？
3、通过这个项目搭建的DNS的上游DNS是哪个？

**Comment by HuanMeng0** [comment]
1.中文Guide：https://github.com/zyqf/DNS/wiki/Guide(zh-CN)
2.上游DNS为全球13组IPv4根DNS服务器
