### ISSUE TITLE
最新代码的问题

### ISSUE THREAD

**Issue by HuanMeng0** [zyqf/DNS#24]
我用网易的docker容器服务进行测试，可能是内核太高/文件缺失的问题，导致在service named start的时候会报错：named: capset failed: Operation not permitted: please ensure that the capset kernel module is loaded.  see  insmod(8)

系统版本为CentOS6.7
内核信息：Linux testdns-41718-a541919f-pd6tc 3.18.20-nce-amd64 #1 SMP Tue Nov 17 09:32:21 UTC 2015 x86_64 x86_64 x86_64 

运行modprobe capability手动加载模块报错：
FATAL: Could not load /lib/modules/3.18.20-nce-amd64/modules.dep: No such file or directory

我用来进行测试的最新代码已经PUSH到了dev分支，修复了路径问题。

**Comment by zyqf** [comment]
编译内核尝试下。

**Comment by HuanMeng0** [comment]
docker编译内核？网易的docker连/etc/grub.conf都没有……

**Comment by zyqf** [comment]
docker 不清楚。 要么就安装老版本的

**Comment by zyqf** [comment]
老版本的安装方式：https://github.com/zyqf/DNS/wiki/Install-with-docker
