### ISSUE TITLE
目前仅支持centos6.5？

### ISSUE THREAD

**Issue by lizhengxian1991** [zyqf/DNS#25]
怎么样安装在ubuntu或者centos7呢

**Comment by zyqf** [comment]
更改install.sh脚本，yum改成sudo apt-get ，可能还有其他一些问题。建议您先自己动手尝试，如果遇到错误，我很乐意与您一起解决。前提是您要自己先尝试动手下，感谢。另外近期是有支持Ubuntu系统的计划的。

**Comment by shizzmk** [comment]
@zyqf 請問下支持Linux全平臺麼？  除了只有RedHat系CentOS?

**Comment by HuanMeng0** [comment]
目前仅支持CentOS，zyqf会在15天内完成对ubuntu的支持。
如果您有能力，可以自行写安装代码并pull request到本项目
