### ISSUE TITLE
无法访问国内网站

### ISSUE THREAD

**Issue by baozhibo** [zyqf/DNS#28]
阿里云ecs  ip ：121.43.61.107
服务正常启动可以访问google wiki  youtube，国内网站都无法找到ip了

**Comment by HuanMeng0** [comment]
怀疑是上游DNS查询失败

**Comment by baozhibo** [comment]
系统centos 6.7 bind是安装版的。有解决办法吗。。现在用俩dns

**Comment by HuanMeng0** [comment]
目前没有遇到过这样的情况，你可以尝试自己解决。

**Comment by baozhibo** [comment]
可以关闭问题了，问题解决
1.设置了selinux=disabled。建议在readme 上写明需要重启服务器，需要重启服务器生效。
2.rcdp的key错误，重生成后重启服务。
谢谢提供安全脚本

**Comment by Tsezz** [comment]
出现同样问题，楼主能说详细点吗

**Comment by HuanMeng0** [comment]
@Tsezz 关闭SELINUX
