### ISSUE TITLE
Can U give me an dnsmasq config file?

### ISSUE THREAD

**Issue by kmahyyg** [zyqf/DNS#3]
RT

**Comment by zyqf** [comment]
Edit /etc/dnsmasq.conf file

you can add

server=/google.com/120.27.30.176
server=/facebook.com/120.27.30.176

thx

**Comment by kmahyyg** [comment]
Thanks a lot.
Close TK.

2016-01-29 13:11 GMT+08:00 zyqf <notifications@github.com>:

> Edit /etc/dnsmasq.conf file
>
> you can add
>
> server=/google.com/120.27.30.176
> server=/facebook.com/120.27.30.176
>
> thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zyqf/DNS/issues/3#issuecomment-176579125>.
>



-- 
Send From My Google Mail

Contact Me:

Twitter:@PotatoOnline
Facebook:Find"Yang Yuguang" (yang.yuguang.73@facebook.com)
QQ:920337808
Tencent Microblog:@kmahyyg @lyxyjg
G+:kmahyygyyg@gmail.com
