### ISSUE TITLE
好像皇家战争访问不正常

### ISSUE THREAD

**Issue by bingbingzhao** [zyqf/DNS#30]
能进游戏 开不了宝箱 无限登陆 麻烦确认下是不是DNS解析问题么

**Comment by HuanMeng0** [comment]
请问是你自己搭建的DNS吗？
如果是，你可以尝试修改上游DNS为防污染DNS，比如科大DNS

[https://github.com/zyqf/DNS/issues/20](https://github.com/zyqf/DNS/issues/20)

**Comment by zyqf** [comment]
你可以更改其他公共DNS，看问题是否还存在。
