### ISSUE TITLE
无法访问 GitHub

### ISSUE THREAD

**Issue by itdevwu** [zyqf/DNS#38]
无法访问 GitHub。国内主流 DNS 可以，基本可以判断问题出在 PandaDNS 上。

**Comment by zyqf** [comment]
在Chrome浏览器地址中输入

* chrome://net-internals/#dns

* 然后按 clear host cache 

* 新建标签页输入GitHub地址

* 在chrome://net-internals/#dns 标签页中查看相关记录

提交给我

**Comment by zyqf** [comment]
过去服务器处于欠费状态，实在抱歉。如果有主机，建议自建。

**Comment by vus520** [comment]
现在github的ip已经变成 192.30.253.112， 192.30.253.113
pd上还是192.30.252.131，可以自己fork一份rpz.zone，然后修改update.php中的路径

**Comment by zyqf** [comment]
@vus520 thanks,修改了服务器记录
