### ISSUE TITLE
如何判定我的bind 的版本是旧版本

### ISSUE THREAD

**Issue by ShangXinbo** [zyqf/DNS#39]
yum remove bind*
这条命令会删除我系统其他的软件

**Comment by zyqf** [comment]
bind.x86_64 32:9.8.2-0.37.rc1.el6_7.6

这个是旧版,那就删掉 yum remove bind bind-libs bind-util 这三个

**Comment by ShangXinbo** [comment]
程序会自动安装最新版本么

**Comment by zyqf** [comment]
bind-libs 这个不会,你只要卸载主程序就行了,bind.x86_64 32:9.8.2-0.37.rc1.el6_7.6 

rpm -qa bind.x86_64 看下是不是安装了

**Comment by ShangXinbo** [comment]
我是用的ubuntu14.04 ，我查看了我的软件信息，没有你说的bind.x86_64 ,有一个 bind9-host                          1:9.9.5.dfsg-3ubuntu0.8          amd64        Version of 'host' bundled with BIND 9.X，是不是最新的bind9，是否可以不用删除了

**Comment by zyqf** [comment]
可以,安装完后,启动bind的话, 直接用命令:named

**Comment by ShangXinbo** [comment]
直接用命令:named是什么意思

**Comment by ShangXinbo** [comment]
No such file or directory: '/usr/local/named/var/rpz.zone' | 
cannot create directory ‘/var/named’: File exists

**Comment by zyqf** [comment]
不公开用这个
https://github.com/zyqf/DNS/wiki/Install-with-docker

**Comment by ShangXinbo** [comment]
啥意思，用docker就不会遇到刚才的问题了？

**Comment by zyqf** [comment]
不不，你直接按步骤敲命令就好了

**Comment by ShangXinbo** [comment]
好吧，我还是不能理解，多谢你的建议
