### ISSUE TITLE
非rpz.zone 域名无法解析bug

### ISSUE THREAD

**Issue by zyqf** [zyqf/DNS#41]
部分国内vps一键安装后，非rpz.zone 域名无法解析，等待解决

**Comment by fangzhengjin** [comment]
centos.sh中将
dig @223.5.5.5 . ns > /usr/local/named/var/named.root;
恢复为
dig @a.root-servers.net . ns > /usr/local/named/var/named.root;
就正常了~

**Comment by zyqf** [comment]
是我的疏忽，没注意到获取的结果不一样，但是国内vps往往解析超时而获取不到记录，另写个循环脚本判断好了。。

**Comment by zyqf** [comment]
ok了，感谢建议，如果后来者看到国内域名都无法解析的情况，可以尝试运行： 
`python /root/DNS/bin/fixns.py`

**Comment by zyqf** [comment]
如果有类似情况的筒靴，可以尝试运行：
```
python /root/DNS/bin/fixns.py
```
