### ISSUE TITLE
麻烦请教下，这个dns 是否可用上级dns 使用5353端口

### ISSUE THREAD

**Issue by ciskonc** [zyqf/DNS#50]
如果能使用5353，具体该如何操作、

**Comment by zyqf** [comment]
```
forwarders { ip_addr [port ip_port] ; [ ip_addr [port ip_port] ; ... ] };
 forwarders { 10.2.3.4; 192.168.2.5; };
```
http://www.zytrax.com/books/dns/ch7/queries.html

```
zone "foo.example.org" {
 type forward;
 forwarders{ 127.0.0.1 port 5353; };
};
```

http://serverfault.com/questions/430269/recursive-forward-a-zone-in-bind

**Comment by ciskonc** [comment]
@zyqf 
zone "." IN {
type forward;
forwarders{ 202.141.162.123 port 5353; };
};
看了半天英文。。一脸懵逼。。。只能看懂一半。。。
麻烦，请教下这样子对不对、

**Comment by zyqf** [comment]
测试下就知道了啊,我也没有弄个这个.

**Comment by ciskonc** [comment]
@zyqf  谢谢指教。可以用。
