### ISSUE TITLE
Google play的apk下载的host

### ISSUE THREAD

**Issue by codexss** [zyqf/DNS#7]
gvt1.com和gvt2.com都是谷歌的域名，希望添加上泛解析。

**Comment by zyqf** [comment]
已添加。
请教几个问题：
一：gvt1.com是否有gvt1.com~gvt999.com ? 还是仅有2个。

二：利用DNS，google play 无法登录，不知是个别现象还是普遍现象，如果是后者，您能否提供相关域名呢？

**Comment by codexss** [comment]
第一个问题，看whois就知道了。
第二个，Google play我这里登录没问题，你用wi.cap看看是哪里通讯出现了问题，我用的是香港运营商的sni代理的。

**Comment by zyqf** [comment]
非常感谢提供wi.cap 这款工具。
