### ISSUE TITLE
请问能开放服务器源代码吗？谢谢！

### ISSUE THREAD

**Issue by itdevwu** [zyqf/DNS#8]
一个小时以前，您终于更新了IP，其中许多IP已经完全不可用了，上一次更新已经是16天前，这样我们即使自建镜像也无法使用。希望您能吧获取可用IP的方法或整个DNS服务器端的代码开源，谢谢！

**Comment by m1911** [comment]
。。。这个dns 就是bind 搭建的要开放什么 他找的ip 都是网上更新的hosts 文件 自己找下不就好了

**Comment by zyqf** [comment]
正在计划写个自动更新脚本，原有的记录形式不太好，所以要抽空去整理，因为这段日子比较忙。...更新不及时，楼上说的很对，大部分找hosts就行了。

**Comment by 51Google** [comment]
有个一键安装脚本就更好了

**Comment by m1911** [comment]
@51Google 。。。都已经yum install bind* 了还需要一件 。。

**Comment by 51Google** [comment]
一键的门槛相对于那么几个步骤来说，更低，也更容易
