### ISSUE TITLE
请问如何搜集没有被屏蔽的IP？

### ISSUE THREAD

**Issue by HuanMeng0** [zyqf/DNS#9]
如题目

**Comment by zyqf** [comment]
github 有 hosts 项目

**Comment by HuanMeng0** [comment]
了解，我往你的邮箱qq767026763@gmail.com发了一封邮件。请您查看

**Comment by HuanMeng0** [comment]
目前的配置文件，似乎无法正常使用Google.cn?

**Comment by zyqf** [comment]
十分感谢，已经合并到项目中。

**Comment by zyqf** [comment]
yeah , 代码先递交了github，服务器那边还没开始同步，正在计划写自动更新脚本

HuanMeng <notifications@github.com>于2016年3月6日周日 下午8:55写道：

**Comment by HuanMeng0** [comment]
find out
